import type { MaterialIcons } from '@expo/vector-icons';
import type { ComponentProps } from 'react';

export type MaterialGlyph = ComponentProps<typeof MaterialIcons>['name'];

export const symbolFallbacks = {
  'house.fill': 'home',
  'list.bullet.rectangle.fill': 'receipt-long',
  'chart.pie.fill': 'pie-chart',
  'gauge.with.dots.needle.33percent': 'speed',
  'gearshape': 'settings',
  'gearshape.fill': 'settings',
  'magnifyingglass': 'search',
  'plus': 'add',
  'plus.circle.fill': 'add-circle',
  'minus': 'remove',
  'minus.circle': 'remove-circle-outline',
  'minus.circle.fill': 'remove-circle',
  'pencil': 'edit',
  'trash': 'delete-outline',
  'trash.fill': 'delete',
  'repeat': 'repeat',
  'square.grid.2x2': 'grid-view',
  'square.split.2x1': 'vertical-split',
  'tag.fill': 'sell',
  'circle': 'circle',
  'checkmark': 'check',
  'checkmark.circle.fill': 'check-circle',
  'xmark': 'close',
  'xmark.circle.fill': 'cancel',
  'delete.left': 'backspace',
  'delete.left.fill': 'backspace',
  'doc.on.doc': 'content-copy',
  'square.and.arrow.up': 'ios-share',
  'square.and.arrow.down': 'file-download',
  'lock.fill': 'lock',
  'faceid': 'face',
  'bell.fill': 'notifications',
  'calendar': 'calendar-today',
  'clock': 'schedule',
  'paintbrush.fill': 'brush',
  'info.circle': 'info-outline',
  'arrow.left.arrow.right': 'swap-horiz',
  'arrow.right': 'arrow-forward',
  'arrow.up': 'arrow-upward',
  'arrow.down': 'arrow-downward',
  'arrow.triangle.2.circlepath': 'autorenew',
  'arrow.uturn.backward.circle.fill': 'undo',
  'chevron.down': 'expand-more',
  'chevron.up': 'expand-less',
  'chevron.left': 'chevron-left',
  'chevron.right': 'chevron-right',
  'ellipsis': 'more-horiz',
  'ellipsis.circle.fill': 'more-horiz',
  'banknote': 'payments',
  'banknote.fill': 'payments',
  'building.columns.fill': 'account-balance',
  'creditcard': 'credit-card',
  'creditcard.fill': 'credit-card',
  'wallet.pass.fill': 'account-balance-wallet',
  'chart.line.uptrend.xyaxis': 'trending-up',
  'chart.bar.fill': 'bar-chart',
  'laptopcomputer': 'laptop-mac',
  'gift.fill': 'card-giftcard',
  'fork.knife': 'restaurant',
  'cart.fill': 'shopping-cart',
  'car.fill': 'directions-car',
  'bag.fill': 'shopping-bag',
  'bolt.fill': 'bolt',
  'book.fill': 'menu-book',
  'cross.case.fill': 'medical-services',
  'play.rectangle.fill': 'smart-display',
  'airplane': 'flight',
  'sparkles': 'auto-awesome',
  'cup.and.saucer.fill': 'local-cafe',
  'wineglass.fill': 'wine-bar',
  'takeoutbag.and.cup.and.straw.fill': 'takeout-dining',
  'birthday.cake.fill': 'cake',
  'pawprint.fill': 'pets',
  'tram.fill': 'tram',
  'bus.fill': 'directions-bus',
  'bicycle': 'directions-bike',
  'fuelpump.fill': 'local-gas-station',
  'parkingsign': 'local-parking',
  'scooter': 'electric-scooter',
  'ferry.fill': 'directions-boat',
  'tshirt.fill': 'checkroom',
  'basket.fill': 'shopping-basket',
  'gamecontroller.fill': 'sports-esports',
  'film.fill': 'movie',
  'music.note': 'music-note',
  'headphones': 'headphones',
  'tv.fill': 'tv',
  'dumbbell.fill': 'fitness-center',
  'figure.run': 'directions-run',
  'heart.fill': 'favorite',
  'pills.fill': 'medication',
  'stethoscope': 'healing',
  'cross.fill': 'local-hospital',
  'bed.double.fill': 'bed',
  'sofa.fill': 'weekend',
  'lightbulb.fill': 'lightbulb',
  'drop.fill': 'water-drop',
  'flame.fill': 'local-fire-department',
  'wifi': 'wifi',
  'iphone': 'smartphone',
  'phone.fill': 'call',
  'envelope.fill': 'mail',
  'wrench.and.screwdriver.fill': 'build',
  'hammer.fill': 'hardware',
  'key.fill': 'vpn-key',
  'graduationcap.fill': 'school',
  'briefcase.fill': 'work',
  'shield.fill': 'security',
  'percent': 'percent',
  'dollarsign.circle.fill': 'monetization-on',
  'giftcard.fill': 'card-giftcard',
  'scissors': 'content-cut',
  'camera.fill': 'photo-camera',
  'leaf.fill': 'eco',
  'tree.fill': 'park',
  'umbrella.fill': 'beach-access',
  'globe': 'public',
  'star.fill': 'star',
  'person.fill': 'person',
  'person.2.fill': 'group',
  'figure.and.child.holdinghands': 'family-restroom',
  'stroller.fill': 'child-friendly',
  'house.and.flag.fill': 'cottage',
  'building.2.fill': 'apartment',
  'questionmark.circle.fill': 'help',
} as const satisfies Record<string, MaterialGlyph>;

export type SymbolName = keyof typeof symbolFallbacks;

export const categoryIconNames = [
  'fork.knife',
  'cup.and.saucer.fill',
  'wineglass.fill',
  'takeoutbag.and.cup.and.straw.fill',
  'birthday.cake.fill',
  'cart.fill',
  'basket.fill',
  'car.fill',
  'bus.fill',
  'tram.fill',
  'bicycle',
  'fuelpump.fill',
  'airplane',
  'bag.fill',
  'tshirt.fill',
  'house.fill',
  'bed.double.fill',
  'sofa.fill',
  'bolt.fill',
  'lightbulb.fill',
  'drop.fill',
  'flame.fill',
  'wifi',
  'iphone',
  'arrow.triangle.2.circlepath',
  'cross.case.fill',
  'pills.fill',
  'heart.fill',
  'dumbbell.fill',
  'play.rectangle.fill',
  'film.fill',
  'music.note',
  'gamecontroller.fill',
  'tv.fill',
  'book.fill',
  'graduationcap.fill',
  'sparkles',
  'scissors',
  'pawprint.fill',
  'gift.fill',
  'banknote.fill',
  'laptopcomputer',
  'briefcase.fill',
  'chart.line.uptrend.xyaxis',
  'dollarsign.circle.fill',
  'building.columns.fill',
  'creditcard.fill',
  'wallet.pass.fill',
  'shield.fill',
  'wrench.and.screwdriver.fill',
  'hammer.fill',
  'camera.fill',
  'leaf.fill',
  'umbrella.fill',
  'globe',
  'star.fill',
  'person.2.fill',
  'stroller.fill',
  'envelope.fill',
  'phone.fill',
  'key.fill',
  'percent',
  'tag.fill',
  'ellipsis.circle.fill',
  'plus.circle.fill',
  'arrow.uturn.backward.circle.fill',
] as const satisfies readonly SymbolName[];

export function resolveGlyph(name: string): MaterialGlyph {
  return (symbolFallbacks as Record<string, MaterialGlyph>)[name] ?? 'circle';
}
